### ISSUE TITLE
TODO #4 Check that configuration file exists and if not use the default.

### ISSUE THREAD

**Issue by mariaclrd** [manuelmorales/tokens_node#5]
Check that configuration file exists or retrieve information from the default instead.

**Comment by sermilrod** [comment]
working on this

**Comment by sermilrod** [comment]
This is on this PR https://github.com/manuelmorales/tokens_node/pull/13/files 

The person who reviews please close this issue.

**Comment by mariaclrd** [comment]
Merge and closed
